### ISSUE TITLE
Truncated output after ampersand

### ISSUE THREAD

**Issue by ExtremeCoolDude** [TowelSniffer/Anki-Chess-2.0#10]
This will result in pegparser syntax error : 

```
[Event "?"]
[Site "?"]
[Date "????.??.??"]
[Round "?"]
[White "?"]
[Black "?"]
[Result "*"]
[ECO "E14"]

1. d4 d5 2. Nf3 { Here black & white look good } 
```

`console.log(pgn)` : 

![image](https://user-images.githubusercontent.com/50034073/112717355-31a5cf00-8f14-11eb-8b56-f9235d1940a7.png)

Everything after `&` character is truncated. Not sure what's causing it

**Comment by TowelSniffer** [comment]
So with URL variables they are separated by an ampersand, so Its no surprise having an ampersand in the pgn will cause an error. The only way I can think to fix it is to replace it with something else and then re-replace it in the html files. Kind of dirty but what can you do. 

I will check to see if other characters trip it, like an Equals sign perhaps

**Comment by TowelSniffer** [comment]
Ok so a clean solution exists. Simply encodeURIComponent instead of encodeURI solves this. this is what I get for trying to use code without reading what it actually does

**Comment by TowelSniffer** [comment]
fixed
