### ISSUE TITLE
how do i get this to work on anki?

### ISSUE THREAD

**Issue by marksteadman080592** [TowelSniffer/Anki-Chess-2.0#11]
how do i get this to work on anki?

**Comment by TowelSniffer** [comment]
To install, Follow the installation instructions on the main page of this repository

For usage, I have a [tutorial](https://youtu.be/goThb7pFIRA) that goes over an older version but it's should help.

**Comment by marksteadman080592** [comment]
can your software add multiple games at the same time to anki?

**Comment by TowelSniffer** [comment]
This is just a card template for Anki, it doesn't import games or generate cards automatically. You have to add the cards yourself. If you have them in the correct csv format then you can add multiple games. I managed to import a few thousand tactics at a time, however, you would probably need some regex knowledge. 

there is another project that makes use of these templates (https://github.com/pwenker/chessli), which should batch create cards, however I never got around to using it. I will close this issue, however if you have more questions you can message me on Reddit (u/Towel_Sniffer) or discord (TowelSniffer#7098)
