### ISSUE TITLE
does anyone know of a way that i can download all of the FEN codes from a book in pdf form onto my computer?

### ISSUE THREAD

**Issue by marksteadman080592** [TowelSniffer/Anki-Chess-2.0#14]

**Comment by TowelSniffer** [comment]
Sorry mate but this is mainly for reporting bugs and feature requests. if you have questions, I gave you my details on Reddit and Discord. 

PDFs aren't the best format, ideally, you want plain text format, but what I'd try to do is try to import the fen codes into an excel spreadsheet and then export that to CSV format. this can then be [imported into Anki](https://apps.ankiweb.net/docs/manual20.html#importing-text-files) however like I said, With PDFs, you can run into all sorts of issues.

**Comment by marksteadman080592** [comment]
so do you know how could get the fens from a pdf or book online and wack
them all into anki quickly without having to do them one by one

TowelSniffer ***@***.***> escreveu no dia quinta, 15/04/2021
à(s) 15:23:

**Comment by TowelSniffer** [comment]
It might be doable if you can convert it to plain text. But I wouldn't know. 

You said in the other issue that the templates don't work, did you manage to fix this or is this still the case
