### ISSUE TITLE
After update, opponents moves don't occur automatically

### ISSUE THREAD

**Issue by inq314** [TowelSniffer/Anki-Chess-2.0#15]
Hi, I just updated anki-chess-2.0.  I first downloaded it when you released it and have been using if ever since then.  After updating all my existing tactics cards don't work right.  After I make the correct move, the opponent should automatically respond, instead I can move the opponents pieces. 

Also i remember you mentioned on reddit that a new update solved the issue of extra lines of code in chess.com puzzles would not interfere with card functionality, but that seems to still be an issue.

Thanks! Love anki-chess 2.0 so much!
-Seth

**Comment by inq314** [comment]
Also the card templates look a bit funny, with some random letters and numbers after them.
![Screen Shot 2021-04-25 at 12 24 53 PM](https://user-images.githubusercontent.com/83177874/116001221-65cae900-a5c1-11eb-80ae-81499eeb3aea.png)

**Comment by TowelSniffer** [comment]
Hey there, so my suspicion is your older cards are using the old template. 

So to fix, sync first or backup, then select all the cards using the old note types, so chess 2.0 for instance, and change there cards typed to the one with the same name but all the letters and numbers after it. They should then work fine.

**Comment by inq314** [comment]
that works!

**Comment by inq314** [comment]
Any comment about the code from chess.com puzzles? 

Here is a puzzle from chess.com:

[Event "?"]
[Site "?"]
[Date "????.??.??"]
[Round "?"]
[White "?"]
[Black "?"]
[Result "*"]
[SetUp "1"]
[FEN "1k6/1P4p1/4p1b1/P3Pp1p/3q1P2/Q7/1r1r2PP/RR5K b - - 0 34"]
**[FirstMove "34w"]
[Puzzle_Length "4"]**

34... Kxb7 35. a6+ Ka7 36. Qe7+ Qd7 37. Qxd7+ Rxd7 38. Rxb2 *


I need to delete the text in bold.  Otherwise the card just reads as blank, no chessboard, no nothing.

**Comment by TowelSniffer** [comment]
I kind of thought that should just work after changing note types but if not this is definitely fixxible. I will be at my computer in like half an hour so I will have a look

**Comment by TowelSniffer** [comment]
In the meantime deleting the bold should fix it

**Comment by TowelSniffer** [comment]
sorry I forgot about checking this.

I ended up checking on my cards though and they seem to work fine. I don't have to remove the bold text. can I confirm you are adding cards selecting the updated note types, so with the numbers afterwards, not the old notes (you can remove those)
