### ISSUE TITLE
Play out all the variations

### ISSUE THREAD

**Issue by ExcitingTrap** [TowelSniffer/Anki-Chess-2.0#16]
When there are couple of variations in a line, Anki randomly chooses a line and the problem ends after we play out that variation correctly, even if that was not the main line of the variation. Instead it should ask us through all the variations. 
For example: Mainline goes 10 moves, but on 5th move there is a 3 move variation. In this case, Anki should make us play through the 3 move variation, and then continue with the mainline.
I understand that there is a feature that makes us play through all the lines, but there we will have to make the moves for both the sides.

**Comment by TowelSniffer** [comment]
Hi there, it's a nice idea, however while possible to set up, it would be quite a hassle for me and considering it's not a feature I would use, I don't see myself implementing this sorry.

I will give my opinion though as I think this approach might have a better solution. If I wanted to memorise every variation to an opening, I would would try to break it down into multiple cards. The random moves were made with tactics and forced mates in mind as they make the cards a lot harder. For long or complicated lines, I would break each line into there own cards, as trying to learn too much from a single card isn't a good idea. 

So in your example, where the mainline goes 10 moves and then splits into 3, you can use my template for the main line and then [This template](https://ankiweb.net/shared/info/1176122148) to show a static position where the mainline splits and just list the variations on the back.

Anyway those are just my thoughts, you are welcome to ignore them.

**Comment by 1shaSharma** [comment]
That is quite a pity. I should say that my lines usually go 23 moves minimum with tons of variations in between so making separate cards is not convenient. Chessable is a good site actually for this, but editing my lines are not as convenient as in your template.

**Comment by TowelSniffer** [comment]
Yeah I feel you. I will say that your desired set-up is definitely possible if you are willing to get your hands dirty with some JavaScript. I never had coding experience before making these templates so don't let that discourage you. And the tricks you obtain can be used with anything else you wish to learn. 

Ima close this for now but feel free to ask me questions via Reddit or discord should you decide to tinker with the templates. I left my details on the shared deck page.
