### ISSUE TITLE
iOS format issue

### ISSUE THREAD

**Issue by problemadder** [TowelSniffer/Anki-Chess-2.0#22]
Does work great on MAC. 👍 Thanks for your great work! 
On iOS (iPhone and iPad) the cards are are not shown fully. Any ideas how to solve the issue?
I have tried to change some values in the css with no success.
![IMG_0981](https://user-images.githubusercontent.com/49922107/213907268-cfb55e47-99a5-4eee-ba43-959865d81b10.PNG)
![IMG_0982](https://user-images.githubusercontent.com/49922107/213907271-6b8e8af2-7d77-4f24-880b-34138985a593.PNG)

**Comment by TowelSniffer** [comment]
Good to know it works on MAC. 

As for this issue on IOS, it looks like an easy fix. However, it will be hard for me to solve without a device to test with so I will need you to test for me if thats doable for you. 

If you go to the iframe section of the CSS:

```
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
```
This section centers the content. removing all that might make it render properly. If you haven't already, can you please that and see if that works. and let me know.

if it does work can you please try changing the values of the translate, ie:

```
  transform: translate(-50%, -0%);
```

**Comment by TowelSniffer** [comment]
if this works it will be easy enough to make some IOS specific CSS and I can update the template

**Comment by TowelSniffer** [comment]
actually before trying my earlier suggestion try changing the following in the body section:

```
body {
  margin: 0;
  height: 100%;
}
```
change `height: 100%;` to `height: 100vh;`. Sorry for the confusion

**Comment by problemadder** [comment]
thank you for the fast replay:
1 attempt: removing:

```
''' position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);'''
```

results in:
![IMG_0983](https://user-images.githubusercontent.com/49922107/213912288-69eba5da-8e57-4e0c-ac86-f7e1c1f03e5f.PNG)
![IMG_0984](https://user-images.githubusercontent.com/49922107/213912291-09d21f51-7bb1-4cbf-9748-e6d5bc8071c0.PNG)

the front card is quite good, but lacks the black border on top.
the back card is quite good, but is missing the bottom part with notation etc

2 attempt: 
"changing height: 100%; to height: 100vh;"

results in:
![IMG_0986](https://user-images.githubusercontent.com/49922107/213912410-895e1967-6d6d-425b-93c8-2aa49f4694f6.PNG)
![IMG_0987](https://user-images.githubusercontent.com/49922107/213912415-02d56d8f-2a50-45ed-988b-301c8a9dac36.PNG)

mentionable: on MAC it does still look good, even with the changes.

so i guess the iframe size and the border size are the last two thinks to fix.
Perhaps you have further ideas

**Comment by TowelSniffer** [comment]
hmmm... annoying that didn't fix it. 

```
body {
  margin: 0;
  height: 100vh;
}
```

I'm thinking maybe making this 

```
.card {
  margin: 0;
  height: 100vh !important;
}
```
and also trying

```
.html {
  margin: 0;
  height: 100vh !important;
}
```

**Comment by problemadder** [comment]
the back card is quite good now, I test your other versions from above later in the evening
![IMG_0989](https://user-images.githubusercontent.com/49922107/213913136-5e1870ea-3d98-4b39-a2be-e0e751162852.PNG)
![IMG_0990](https://user-images.githubusercontent.com/49922107/213913137-f3a48498-a419-4d44-a223-fd03e2a9e608.PNG)

**Comment by TowelSniffer** [comment]
another approach would be to maximize the iframe container on IOS which should make it usable?
so something like:

```
/* iOS */
.iphone iframe, .ipad iframe {
  height: 100vh !important;
  width: 100vw !important;
}
```

**Comment by TowelSniffer** [comment]
yeah ok, thanks for your help

**Comment by problemadder** [comment]
after some try and error i have a solution that works good for me (i guess its not "clean" at all), that is how it looks on ipad and iphone:
![IMG_0994](https://user-images.githubusercontent.com/49922107/213923061-378850eb-1c19-4c87-864f-d65727d9a5ea.PNG)![IMG_0995](https://user-images.githubusercontent.com/49922107/213923065-3e087998-34a4-4e91-ba9d-305aab866d2c.PNG)
thats how it looks on mac:
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/49922107/213923113-85842170-e6c5-4e3f-b202-4d19d1f9a046.png"><img width="834" alt="image" src="https://user-images.githubusercontent.com/49922107/213923151-ba811239-36f3-4ec1-ac99-b7c4b0d0518c.png">
for my solution i changed the back template to: <`iframe id="analysisBoard" allowtransparency="true" class="solution"></iframe>`
and the CSS to:
```
body {
  margin: 0;
	height: 100vh;
}

.mac iframe {
  height: min(550px, 100vw);
  width: min(550px, 100vw);
  border: 0;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  border: 1px solid #94e2d5;
	border-radius: 4px;
  box-shadow: 0px 0px 4px 0px #94e2d5;
}

/* iOS */
.iphone iframe, .ipad iframe {
  height: 90vh !important;
  width: 100vw !important;
}

.solution {
	width: min(400px)!important;
  height: min(520px, 100vw !important;
}
```
thanks again! I use your cards nearly every day for some chess anki reps from blunders (plenty 😅 ) from my games and tactics 👍

**Comment by TowelSniffer** [comment]
Brilliant, thanks for the help, and you're welcome. I will update the repository tomorrow morning with this solution. not clean, but functional is as good as can be hoped for unless I can get my hand on an IOS device (My brother has anki on Iphone, so maybe soon). 
anyway thanks again, and good luck with your chess.
