### ISSUE TITLE
Board image appears cut in half?

### ISSUE THREAD

**Issue by pj-paul** [TowelSniffer/Anki-Chess-2.0#23]
Platform: Mac

![Front side first half](https://user-images.githubusercontent.com/50706721/214584015-5383d1af-6dd8-4c1f-a649-6563b563b2e5.JPG)

![Front side second half](https://user-images.githubusercontent.com/50706721/214584020-2a297db3-50d4-4f78-8c84-c565087a0a97.JPG)

**Comment by problemadder** [comment]
Hi, have a look at the last entry here: https://github.com/TowelSniffer/Anki-Chess-2.0/issues/22
works for me on MAC

**Comment by problemadder** [comment]
for my solution i changed the "back template" to: <iframe id="analysisBoard" allowtransparency="true" class="solution"></iframe>

and the CSS to:

body {
  margin: 0;
	height: 100vh;
}

.mac iframe {
  height: min(550px, 100vw);
  width: min(550px, 100vw);
  border: 0;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  border: 1px solid #94e2d5;
	border-radius: 4px;
  box-shadow: 0px 0px 4px 0px #94e2d5;
}

/* iOS */
.iphone iframe, .ipad iframe {
  height: 90vh !important;
  width: 100vw !important;
}

.solution {
	width: min(400px)!important;
  height: min(520px, 100vw !important;
}

**Comment by pj-paul** [comment]
Ok. This is what worked for me:

```
.mac iframe {
  height: 90vh;
  width: 80vw;
  border: 0;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  border: px solid #94e2d5;
	border-radius: 4px;
  box-shadow: 0px 0px 4px 0px #94e2d5;
}
```

**Comment by pj-paul** [comment]
Closing this.

**Comment by TowelSniffer** [comment]
thanks @problemadder for the help. 

So these inconsistencies on mac and IOS are a bit weird, but I am thinking the issue is with people having different resolution screens. I think I will just update the template so that both iframes span the entire page. 

so update the back template to `<iframe id="analysisBoard" allowtransparency="true"></iframe>` and the css to:

```
.card {
  text-align: center;
  font-size: 20px;
  margin: 0 !important;
}

body {
  height: 100vh;
  width: 100vw;
  /* removes wierd overflow issues on different devices */
  overflow: hidden;
}

iframe {
  height: 100vh;
  width: 100%;
  border: 0;
}
```
This should be more consistent

**Comment by TowelSniffer** [comment]
ok so I just pushed a release that I am happy with. It includes dynamic background coloring so the iframes will automatically style to your background color (this used to be easier when anki allowed transparent backgrounds for iframes). It works well for desktop and android, but i was hoping one of you could test for IOS

**Comment by problemadder** [comment]
Hi TowelSniffer, looks perfect on Mac 👍Front looks perfect on iPhone. Back not so much, Board is very good, but  the notation is not complete and you cant swipe down to see the complete notation (only two lines are visible):
![IMG_1007](https://user-images.githubusercontent.com/49922107/214927424-97eff534-1490-4996-bef7-7ec9a4d2f9f4.PNG)![IMG_1008](https://user-images.githubusercontent.com/49922107/214927429-97632755-5969-46f5-a9a1-3c02d4f66d90.PNG)

**Comment by TowelSniffer** [comment]
It looks like you are still using the old html files?

**Comment by TowelSniffer** [comment]
So this is what it should look like

![Screenshot_20230127-095605_AnkiDroid.jpg](https://user-images.githubusercontent.com/52064198/214976522-c9a6fcfc-b8f2-453a-8a56-5732aa6e95cb.jpg)

![Screenshot_20230127-095551_AnkiDroid.jpg](https://user-images.githubusercontent.com/52064198/214976531-e93b0433-fa4d-43d5-b783-8186d22fd206.jpg)

**Comment by TowelSniffer** [comment]
As for the bottom being cut off, have you tested it with a larger pgn. 

![Screenshot_20230127-100003_AnkiDroid.jpg](https://user-images.githubusercontent.com/52064198/214977132-d998c870-c5f0-4afa-bd34-9920c5e22e82.jpg)

![Screenshot_20230127-095955_AnkiDroid.jpg](https://user-images.githubusercontent.com/52064198/214977155-677390f6-613f-490f-839e-de347553405a.jpg)

That's what I get, it still cuts off a bit at the bottom but does allow me to scroll. It should be easy to fix the bottom being cut off, but why it centres poorly on iPhone idk. This is what I get with a short pgn

![Screenshot_20230127-095912_AnkiDroid.jpg](https://user-images.githubusercontent.com/52064198/214977334-581e9ce9-0dfa-4c5d-b8e6-3a57a6e042ea.jpg)

**Comment by TowelSniffer** [comment]
Actually it looks like the html for iPhone includes the section under the buttons. It seems like the move list it desplayed underneath. And if you consider that then the board is centered

**Comment by problemadder** [comment]
Good morning. No I created an additional completely new deck and a new
user. And than imported the new Anki file and the new html. With complete
reupload to iphone

**Comment by TowelSniffer** [comment]
Are you sure you downloaded the latest release? because  your background color is set to #1E1E2E. This should not happen with the new template, unless that is anki mobiles default background color (which would be a crazy coincidence). can i ask if the background color is auto adjusting on desktop for you? because if so it must be using the old html file on mobile for some reason. 

anyway Don't worry about this too much. I am just going to wait until I can obtain an iphone to test with. thanks again for the help

**Comment by problemadder** [comment]
you are right. i clicked the wrong link in my mails. I tried the newest release.
now the background of the front card is white. but the "notification" problem is still the same. keep up the good work. i roll back to my manipulated version that works very fine for me 👍  have a nice weekend.
