### ISSUE TITLE
Piece behavior for error moves?

### ISSUE THREAD

**Issue by pj-paul** [TowelSniffer/Anki-Chess-2.0#24]
https://user-images.githubusercontent.com/50706721/214648009-c4e77eb8-3b82-4404-993f-3dba091dde71.mp4

I'm not quite sure what the current version is meant to provide, but the game-play differs a bit from expectations. Error moves must be flagged somehow? For example, I tried to play 1. Ne4+, the card did not allow my move and instead automatically played 1.f1=N+.

**Comment by problemadder** [comment]
you have to change to "handicap = 1;" in the html.
so you have the choice how many "tries" are allowed before the solution is shown

**Comment by pj-paul** [comment]
Ah, missed that. Thanks a ton.
