### ISSUE TITLE
File not found on Ankidroid

### ISSUE THREAD

**Issue by modess** [TowelSniffer/Anki-Chess-2.0#25]
Works perfect on Linux for me, but not on my phone 😔 Error message says: "Website not available... Could not read in website at: ..."

Android 12
Ankidroid 2.15.6

```
Webbsidan är inte tillgänglig

Det gick inte att läsa in webbsidan på file:///storage/emulated/0/AnkiDroid/collection.media/_chess3.0.html?PGN=%5BVariant%20%22From%20Position%22%5D%5BFEN%20%226k1%2Fb2n1pp1%2F5n1p%2F4N3%2F8%2F6P1%2FP2R1P1P%2F6K1%20w%20-%20-%200%201%22%5D1.%20Nxd7%20Nxd7%202.%20Rxd7&flip=false&handicap=0&background=rgb(0,%200,%200). Orsak:

net::ERR_FILE_NOT_FOUND
```

**Comment by TowelSniffer** [comment]
It looks like the file is not in your media folder for ankidroid 

I have tested a lot of devices on android and they all worked perfectly. Can you check if the `_chess3.0.html` file is on you android device. And make sure you are syncing media.

**Comment by modess** [comment]
Very strange. All other assets were synced, but not the html files. I manually downloaded the media files on my phone and copied them to the folder and now it works. 

Even works after doing a force sync from ankiweb.

**Comment by TowelSniffer** [comment]
yeah that's weird, it should sync any file that starts with an underscore. Good to hear that it works

**Comment by modess** [comment]
Thanks for quick replies and an awesome tool! 🙏
