### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by modess** [TowelSniffer/Anki-Chess-2.0#27]
I'd like to make some changes/improvements, do you have a build process you can share?

**Comment by TowelSniffer** [comment]
well, just editing the html files or the template styling would be the way to make changes. as far as building I just use anki's export feature. I will warn you that the the HTML files especially are not the most legible to understand. this template was made with a figure it out as you go combined with a lot of trial and error, so the result is a mess. The template modifies one of the examples provided with the [chessground repository](https://github.com/lichess-org/chessground) if you want to try and make something from scratch. Feel free to ask me any questions though.
