### ISSUE TITLE
[Feature Request] Specify side for flip=false

### ISSUE THREAD

**Issue by Dazaisan99** [TowelSniffer/Anki-Chess-2.0#30]
I just started using this template and it's amazing! I'd just like to have the option to specify which side I want to play : I'm studying openings, and for defenses such as the dutch, I'd like to have white play the first move and me being black to respond.

I'm okay with code, if you have any idea how I could implement this please tell me, unless you are already planning to add it.

Thanks!

**Comment by TowelSniffer** [comment]
Hi sorry for the delayed response. I'm not sure i Understand your request. By default this template is set up to play the second move of a PGN. So if you input a PGN where white plays first then you will be responding as black. Are you  wanting it to always be black to play and auto switch the flip variable depending on the first move of the PGN?

**Comment by thiotepamoa** [comment]
Yes!

Or is it possible to toggle which side you're on without having to change the card's script (i.e. changing the flip=true/false)?

**Comment by TowelSniffer** [comment]
Hi sorry for the long delay. I seems a bit of a niche feature to include on my template. I'd really like an option to include a shortcut/button to rotate the board but it will end up being a lot of work for something I wont use.

**Comment by thiotepamoa** [comment]
No problem. Thanks for getting back!
