### ISSUE TITLE
Pieces on top of the board on ios (sometimes)

### ISSUE THREAD

**Issue by problemadder** [TowelSniffer/Anki-Chess-2.0#36]
I experience this since iOS 17.4.1.  - from time to time the back of the card is broken, but not all the time. (the last version of anki-chess-2.0 is installed):

https://github.com/TowelSniffer/Anki-Chess-2.0/assets/49922107/aec05649-cb63-4f9c-b89a-5590d80a118b

Recent Anki Update to ⁨24.04 did not help (both Mac and Iphone).

IpadOS 17.3.1 works fine. (17.4.1 testing tomorrow) -> update! - > the problem seems to be 17.4.1 after update on IpadOS to 17.4.1 i have the same issue on Ipad

Perhaps somebody has any idea?

**Comment by problemadder** [comment]
the cards are basically unusable on mobile and ipad now... 
how somebody will find a workaround.

**Comment by TowelSniffer** [comment]
Hi sorry for the delayed response. Unfortunately without an IOS device to test it is very hard for me to maintain this template for IOS. 

[This link](https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#via-eruda-console-for-mobile-browsers) seems promising for being able to access the console log on anki mobile. Would you be able to try it out and see if it provides some kind of error message?

**Comment by problemadder** [comment]
The "logger" does not work on anki mobile only on ankidroid?!. I can see a "log" overlay button  etc but everything is empty when I use it.  I wonder why nobody else has started the issue. I would guess there are other users of your cool chess cards.
When I open the card template on the iPhone. I have a preview function of the card and can edit the css etc. when i use a preview of the card there it works the first time - the second time I get the Error "A javascript exception occurred". 
[RPReplay_Final1713102776.webm](https://github.com/TowelSniffer/Anki-Chess-2.0/assets/49922107/9db8dd80-6770-4b5a-8c1a-d4d3c10af31e)

**Comment by TowelSniffer** [comment]
Would be nice if it told you what the error was lol. I will have a look into this. It might be an anki persistence issue? Seeing as it fails the second time. Is it always just the backside of the card with problems?

**Comment by problemadder** [comment]
Yes. Only the backside

**Comment by xvdd** [comment]
The same issue raised on Anki forum: https://forums.ankiweb.net/t/anki-mobile-javascript-problems/43603

@ TowelSniffer: let us know if you need help to test an updated version with updated libs. I'm also able to replicate the issue consistently when I preview and flip the card.
Pressing flip white/black board orientation in the back side of the card also triggers the misalignment of the pieces.

**Comment by TowelSniffer** [comment]
OK, so I was actually able to recreate this using gnomes web browser "Epiphany". This makes sense as Epiphany is based in safari's web viewer I think. Anyway the issue seemed to be related to the coloured border I added to track errors. Could you try replacing your _ChessTempoViewer.html file thith [this one](https://drive.google.com/drive/folders/1NCNyDcmVZWsUyK9R9UJxbfXZCpsZv97F?usp=sharing) and see if that fixes it as it seemed to solved the problem for me. 

The javascript exeption has occurred error may be something unrelated as I wasn't getting any error messages with epiphany related to this issue so hopefully we can ignore that.

**Comment by problemadder** [comment]
Seems to be working!🌞 no error while reviewing the cards until now. I only
can recreate it when in „card template“ and tapping preview the second
time. The first time it works. So the problem is fixed 🙌thank you very much

**Comment by xvdd** [comment]
Also tested the updated _ChessTempoViewer.html file successfully in review and preview modes.
I realize now that I didn't have the latest https://github.com/TowelSniffer/Anki-Chess-2.0/blob/main/Media%20Files/_ChessTempoViewer.html

Flipping the white and black sides in the back of the card still breaks but I'm not using the feature.

Thank you!

**Comment by TowelSniffer** [comment]
@xvdd Thanks for the report. I should be able to fix the flip button easy enough. I'll post an updated release tomorrow if all goes well.

**Comment by problemadder** [comment]
True. I don’t use it too. ->
Flipping the white and black sides in the back of the card still breaks

**Comment by ThoughtfulSenpai** [comment]
> @xvdd Thanks for the report. I should be able to fix the flip button easy enough. I'll post an updated release tomorrow if all goes well.

Excuse me, did this get fixed? In most recent releases the flip button still breaks the pieces and board. (back of the card) I cannot seem to find any commit addressing this.
works fine
![IMG_7305](https://github.com/user-attachments/assets/5a69367f-75b1-4608-a0d8-1499dbca614a)
![IMG_7306](https://github.com/user-attachments/assets/56dca5a7-6ffb-4506-83d0-7a2b9620f61c)



but back breaks when flipping orientation.

![IMG_7307](https://github.com/user-attachments/assets/26b03801-c8d7-413d-beba-361e389177b2)

**Comment by TowelSniffer** [comment]
@ThoughtfulSenpai Yeah it's annoying. It was solved for me on the browser I was using to replicate this issue. Because I can no longer replicate it it makes it much harder for me to fix as I don't have an IOS device.
