### ISSUE TITLE
Analysis board breaks if PGN comments contains a string " [%" (open bracket and percent sign)

### ISSUE THREAD

**Issue by demiaus** [TowelSniffer/Anki-Chess-2.0#37]
Lichess export puts evaluation info as a PGN comment inside brackets like this

```
{ (1.73 → 8.02) Blunder. Rac2 was best. [%eval 8.02] (player's move was Qa3) }
29. Qf5 Rac2 30. Rd1 1-0
```

The combination of an open bracket and a percent sign makes the Back Template analysis board break. 

Workaround is to select all the cards and use Anki's Find and Replace function to replace all % with a space

**Comment by TowelSniffer** [comment]
Hi thanks for your report. Sorry for the late response but I this should be to automate in the template. I need to post an update soon anyway so I will include a fix for this. hopefully on my next day off

**Comment by TowelSniffer** [comment]
fixed
