### ISSUE TITLE
Can the autoplay button be activated somehow?

### ISSUE THREAD

**Issue by ThoughtfulSenpai** [TowelSniffer/Anki-Chess-2.0#41]
pgn viewer's layout vs on ankis implementation

<img width="299" alt="image" src="https://github.com/user-attachments/assets/9cf8c780-c2c5-4ac2-a268-624a23979627">

<img width="200" alt="image" src="https://github.com/user-attachments/assets/42205fef-d87d-4ff8-bb24-6fb20cee7845">

Hey, I can see that these use pgn-viewer, but I can not find the button for autoplaying the moves anywhere. I tinkered around the _chesstempoviewer_html files, but it seems that the button was consciously deactivated or deleted. (probably by you as a personal decision). Is this the case? 
I would like to get the button back, if possible.  Do you know somehow how to do it?
also, if at all could it be possible to remove the notation for chesstempoviewer.html so that it just shows the board with the buttons below, it would be awesome for certain activities. 

Many, many thanks and have a nice day.

AS A SIDENOTE NOT RELATED: I used the template to create a "recall the position" type of card, once I debug, should I do a pull request?
<img width="300" alt="image" src="https://github.com/user-attachments/assets/14d67b14-7a60-469d-8c45-ea155a1c7f64">
<img width="300" alt="image" src="https://github.com/user-attachments/assets/d8c771d7-6bc7-4a9e-885f-ea9aba12579b">

**Comment by TowelSniffer** [comment]
Hi, it's possible that I removed it though I don't remember nor can I think of a reason why I would have. Id guess the autoplay button is an updated feature for the pgn viewer that wasn't a thing when I made the template. I will look into this when I get off work. 

Also yea pull requests are welcome

**Comment by TowelSniffer** [comment]
I added this back, was hidden in the css
