### ISSUE TITLE
Created a companion app for the template

### ISSUE THREAD

**Issue by ThoughtfulSenpai** [TowelSniffer/Anki-Chess-2.0#47]
https://github.com/ThoughtfulSenpai/AnkifyPGN

Hey, just wanted to post here, if permitted, that I put together a very rough app for making it easy to create flashcards which are compatible with the template. Since I myself was using the template a lot and formatting my files with a script, I put together a GUI so that other people may be able to use it and add custom tactics or puzzles in bulk to anki quickly.

It can generate a text file ready for anki of a whole book of tactics in a second. Then you just import it in conjunction with this template and play. Say you have a pgn for a puzzle book, with thousands of positions. This app will format the pgn into lines so that anki detects each game as one individual flashcard. Add in bulk the cards to the deck.

![image](https://github.com/user-attachments/assets/757e1cd7-a50d-47b8-9166-17a0e806e1a9)

**Comment by MrPropre84700** [comment]
Great plugin !

**Comment by TowelSniffer** [comment]
very cool! I will add this to the readme thanks

**Comment by ThoughtfulSenpai** [comment]
> very cool! I will add this to the readme thanks

Now an anki addon also, so that one can import the pgn without leaving ANKI. Just select the PGN file and in conjunction with this template, have a deck ready in seconds. https://ankiweb.net/shared/info/569467423
