### ISSUE TITLE
backside of card does not load after new release

### ISSUE THREAD

**Issue by problemadder** [TowelSniffer/Anki-Chess-2.0#48]
Hi,
the new sound addition is great! 
but sadly, the back of the cards does not load at all (on mac), but it seams to work great on iphone.
any ideas?

**Comment by TowelSniffer** [comment]
I'm not sure. are you able to see if there are any console error messages with this https://ankiweb.net/shared/info/31746032

**Comment by problemadder** [comment]
ah. yes there are errors:
![Screenshot 2024-12-21 at 18 36 41](https://github.com/user-attachments/assets/cb4a187a-4686-4f57-8804-08a08d669da0)

**Comment by TowelSniffer** [comment]
Might have solved this. Can you try this file?

https://drive.google.com/drive/folders/1TBBMjzf0ks_hAqWRDHXY1TfkL5bQEaiT?usp=drive_link

**Comment by problemadder** [comment]
great. now it seems to be working on both. osx and ios! thanks for the fast fix!
