### ISSUE TITLE
Addition of time taken / "wrong moves" to back of card?

### ISSUE THREAD

**Issue by charlesoblack** [TowelSniffer/Anki-Chess-2.0#5]
Would it be possible to add the time taken to solve the card + how many "wrong moves" were made to the back of the card? It might help with deciding on hard/good/easy.

Thanks so much for the amazing template.

**Comment by TowelSniffer** [comment]
It's not somthing I am personally big on, but having a few customisable options you can enable in the template might be a nice feature. I want to implement an option for multiple themes for pieces, so I can add some other options like a timer and error tracker while I'm at it. 

I have spent a lot of time on these templates recently so I have to catch up on other things right now, but I see no reason why I can't implement this in the future. Though in the meantime, if you are capable with coding, I do take pull requests.

**Comment by TowelSniffer** [comment]
So after considering this a bit longer I probably won't implement this. It just doesn't appeal to me personally and it seems like a niche desire.

**Comment by charlesoblack** [comment]
Aw dang. Woke up to the first comment and was gonna see if I could figure
out the JS (I'm a Python guy) :(

I imagine it would just be additional JS put in the card front/back. If I
did make a PR - would you accept it?

**Comment by TowelSniffer** [comment]
Well there are two concerns that I have and why I decided this would be a hassle. 

You say you are a python guy, so I'm not sure how much html/JavaScript you know but I will try to explain how the cards work. 

Basically the templates mainly just load iframes linking to html files in the collection.media folder (scripts just behave when isolated within an iframe in anki and these cards rely on a lot of scripts). And with any visible content, for aesthetic reasons (mainly with scaling access various screen sizes like mobile) I have it all contained within the iframe. 

So one challenge is passing information from the front to the back. Normally you could use anki persistence and this would be simple, bit with this we would need to get the information from the iframe and pass it to the iframe on the backside, which is less straight forward. Not impossible though, as with the engine template, you may have noticed that all the moves you play are passed to the pgn viewer on the backside so it can be done. 

The other concern is that I wouldn't want the timer personally, it would just be clutter, so it would have to be an optional feature. 

Anyway you can see why I was saying this is a pain in the arse haha, but if you want to do the work in a way that addresses my concerns then I will be happy to help you out. (I can go over how to set it up in more detail when I get back to my computer).

Also I was thinking about the mistake counter, but one idea that I like is passing the attempted mistakes as perhaps comments before the move on the backside (might be easy enough but I'm not sure), that way you can use the pgn viewer to explore your mistakes.

**Comment by charlesoblack** [comment]
Ah, this looks a lot more complex than I imagined.

For the iframes: since there is already the engine template, I imagine that this is possible, yeah.

For the optionality: this one looks more difficult to me - keeping some option set across cards/anki restarts... that sounds more like addon territory. I was thinking that you had custom front/back code in your template somewhere, and it would have been as simple as copy-pasting in/out some lines of code; but with the way you've set it up it does seem a lot more difficult.

So you're right - I don't want it enough that it would be worth that hassle :P Thank you nonetheless though. If this issue someday gets enough attention I can try making a PR in the future! But for now I will just enjoy the work you've already put in. :)

**Comment by TowelSniffer** [comment]
Too easy, but just to mention here what I was suggesting, for the optionality, I was thinking of just having a div just depending on a boolean. so In the engine template, there is the variable "thinkTime" which is passed to the iframe to tell the engine how long to think for, but I could easily set up a similar thing like var timer = true and then have the timer only show if it's set to true. My idea is to have other option like var pieceTheme = meridia for example. 

some customizability is something I want to add in the future and implementing a timer while I'm at it probably wouldn't take too long, and I do like the idea of tracking your mistakes, so I will keep it in mind next time I decide to implement some changes.
