### ISSUE TITLE
Feature Request: Being able to do moves for both you and opponent.

### ISSUE THREAD

**Issue by pwenker** [TowelSniffer/Anki-Chess-2.0#7]
Told you a couple of times, but I'm telling you again: Your card templates are absolutely awesome!

It would be great, if it was possible to have either 
1) An additional card type, or 
2) A conditional field for the existing card types (except the "vs. engine"), which can be filled to enable doing all moves.

For example, if you want to study an opening, with the current card templates, you'll only need to remember and reproduce your own moves (or that of your opponent, depending on the card type) because the respective other moves are made automatically.
This of course makes the task a bit easier, than it should be. And there are probably other use cases, where it would be nice to having to perform all the moves. 

Is this something that can be achieved easily by only changing a few lines of the code? 
If a whole new card type, or a change to add a conditional field is not desired, I would also appreciate a quick guidance on how to implement it myself, if it does not require too much.

**Comment by TowelSniffer** [comment]
This shouldn't be too hard to setup with just an additional field. You would just need to add another URL variable that depends on the field. Then just adding another condition to the relevant if statement in the html files should work (should be two from memory).

I wouldn't mind setting this up on my next day off as it's a good suggestion and seems easy enough. 

The issue with quick guidance is that I wouldn't really know until I did it myself.

**Comment by TowelSniffer** [comment]
last update should work for you
